### ISSUE TITLE
Output the detail to handle the error flexibly

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/deny-self-approve-action#16]
```yaml
- uses: suzuki-shunsuke/deny-self-approve-action@85a0ec0a189b083a84a95d37766f6f6df5aea1ba # v0.1.0
  id: validation
  continue-on-error: true
- name: Post a comment to GitHub
  if: steps.validation.succeeded == 'false'
  run: |
    # ...
```

## Output

```yaml
succeeded: false
commits:
```

## Note

- https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error
